### ISSUE TITLE
Login Problem

### ISSUE THREAD

**Issue by gopiveerla** [zyztek/Magoware#1]
Hi, I Just installed Magoware from your source code in UBUNTU and Mysql is Database. After successful installation i'm not able to login using admin and password : admin. Its just logged in and logged out in a fraction of seconds.But in URL i changed admin name to Dashboard it's login successfully.
![Screenshot from 2021-02-14 14-46-52](https://user-images.githubusercontent.com/26854490/107872867-8563d800-6ed3-11eb-952f-f779660be4d7.png)
 Can you please help me out of this issue.
![Screenshot from 2021-02-14 14-28-21](https://user-images.githubusercontent.com/26854490/107872791-c8717b80-6ed2-11eb-965e-eb4cacb4c337.png)
![Screenshot from 2021-02-14 14-28-28](https://user-images.githubusercontent.com/26854490/107872792-cad3d580-6ed2-11eb-8869-fc9fc87bc4aa.png)

**Comment by zyztek** [comment]
Try this combination
Usr: superadmin
Pss:superadmin
Letme know...
Also, can you share the installation commands you use...install guide...

**Comment by gopiveerla** [comment]
> Try this combination
> Usr: superadmin
> Pss:superadmin
> Letme know...
> Also, can you share the installation commands you use...install guide...
